print("escriba si o no para las variables")
print("ingrese si el aeropuerto de Chile esta disponible")
aeropuerto_Chile = input()
print("ingrese si el aeropuerto de Francia esta disponible")
aeropuerto_Francia = input()
print("ingrese el monto retirado")
afp_retiro = input()
print("pedro estas vacunado?")
vacuna_pedro = input()
print("tu pareja esta vacunada?")
vacuna_pareja = input()
print("Valor del dolar")
dolar = input()
dolar= int(dolar)
afp_retiro = int(afp_retiro)
if (vacuna_pedro == "si" and vacuna_pareja == "si" and afp_retiro >= (7500*dolar) and aeropuerto_Francia == "si" and aeropuerto_Chile== "si"):
    print("puedes ir ")
else :
    print ("no puedes ir")
